package all

import (
	// Active file systems
	_ "github.com/sdhealth/rclone/backend/alias"
	_ "github.com/sdhealth/rclone/backend/amazonclouddrive"
	_ "github.com/sdhealth/rclone/backend/azureblob"
	_ "github.com/sdhealth/rclone/backend/b2"
	_ "github.com/sdhealth/rclone/backend/box"
	_ "github.com/sdhealth/rclone/backend/cache"
	_ "github.com/sdhealth/rclone/backend/crypt"
	_ "github.com/sdhealth/rclone/backend/drive"
	_ "github.com/sdhealth/rclone/backend/dropbox"
	_ "github.com/sdhealth/rclone/backend/fichier"
	_ "github.com/sdhealth/rclone/backend/ftp"
	_ "github.com/sdhealth/rclone/backend/googlecloudstorage"
	_ "github.com/sdhealth/rclone/backend/googlephotos"
	_ "github.com/sdhealth/rclone/backend/http"
	_ "github.com/sdhealth/rclone/backend/hubic"
	_ "github.com/sdhealth/rclone/backend/jottacloud"
	_ "github.com/sdhealth/rclone/backend/koofr"
	_ "github.com/sdhealth/rclone/backend/local"
	_ "github.com/sdhealth/rclone/backend/mega"
	_ "github.com/sdhealth/rclone/backend/onedrive"
	_ "github.com/sdhealth/rclone/backend/opendrive"
	_ "github.com/sdhealth/rclone/backend/pcloud"
	_ "github.com/sdhealth/rclone/backend/premiumizeme"
	_ "github.com/sdhealth/rclone/backend/putio"
	_ "github.com/sdhealth/rclone/backend/qingstor"
	_ "github.com/sdhealth/rclone/backend/s3"
	_ "github.com/sdhealth/rclone/backend/sftp"
	_ "github.com/sdhealth/rclone/backend/swift"
	_ "github.com/sdhealth/rclone/backend/union"
	_ "github.com/sdhealth/rclone/backend/webdav"
	_ "github.com/sdhealth/rclone/backend/yandex"
)
